package entities;
// Generated Apr 17, 2017 3:41:15 PM by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Client generated by hbm2java
 */
@Entity
@Table(name = "Client", catalog = "paperless")
public class Client implements java.io.Serializable {

	private int id;
	private String nome;
	private String nif;
	private String morada;
	private String telefone;

	public Client() {
	}

	public Client(int id) {
		this.id = id;
	}

	public Client(int id, String nome, String nif, String morada, String telefone) {
		this.id = id;
		this.nome = nome;
		this.nif = nif;
		this.morada = morada;
		this.telefone = telefone;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "Id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "Nome", length = 50)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "Nif", length = 50)
	public String getNif() {
		return this.nif;
	}

	public void setNif(String nif) {
		this.nif = nif;
	}

	@Column(name = "Morada", length = 50)
	public String getMorada() {
		return this.morada;
	}

	public void setMorada(String morada) {
		this.morada = morada;
	}

	@Column(name = "Telefone", length = 50)
	public String getTelefone() {
		return this.telefone;
	}

	public void setTelefone(String telefone) {
		this.telefone = telefone;
	}

}
